apiVersion: neuron/v1
kind: Capability

metadata:
  name: capture-payment
  version: 1.0.0
  description: Capture payment

spec:
  capability runtime:
    type: neuron:core:set
    runtimeConfig:
      execution:
        mode: wait
        timeout: 5s

  config:
    capture_result:
      status: succeeded
      amount_received: 7997

  mappings:
    - direction: input
      source: payment_intent_id
      target: payment_intent_id
