apiVersion: neuron/v1
kind: Capability

metadata:
  name: validate-order
  version: 1.0.0
  description: Validate incoming order request

spec:
  capability runtime:
    type: neuron:core:set
    runtimeConfig:
      execution:
        mode: wait
        timeout: 5s

  config:
    status: validated
    valid: true

  mappings:
    - direction: input
      source: execution.params.order
      target: order
