// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: shared/protocol/capabilityruntime/v1/capability_runtime.proto

package capabilityruntimev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CapabilityRuntimeService_Initialize_FullMethodName = "/neuron.capability_runtime.v1.CapabilityRuntimeService/Initialize"
	CapabilityRuntimeService_Execute_FullMethodName    = "/neuron.capability_runtime.v1.CapabilityRuntimeService/Execute"
	CapabilityRuntimeService_Health_FullMethodName     = "/neuron.capability_runtime.v1.CapabilityRuntimeService/Health"
	CapabilityRuntimeService_Shutdown_FullMethodName   = "/neuron.capability_runtime.v1.CapabilityRuntimeService/Shutdown"
)

// CapabilityRuntimeServiceClient is the client API for CapabilityRuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CapabilityRuntimeService is the gRPC contract that capability runtime
// processes implement. N.O.R.E. acts as the client; the capability runtime
// process acts as the server. This protocol is language-independent:
// capability runtime authors can implement it in Go, C#, Java, Rust, Python,
// C++, or any language with gRPC support.
//
// The lifecycle is:
//  1. N.O.R.E. starts the capability runtime process (or connects to one).
//  2. N.O.R.E. calls Initialize to negotiate protocol version and exchange identity.
//  3. N.O.R.E. calls Execute for each execution request.
//  4. N.O.R.E. periodically calls Health to verify the runtime is alive.
//  5. N.O.R.E. calls Shutdown for graceful termination.
type CapabilityRuntimeServiceClient interface {
	// Initialize negotiates the protocol version and exchanges capability
	// runtime identity.
	// Called once per capability runtime process lifetime, before any Execute calls.
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error)
	// Execute runs one capability execution and returns the result.
	// The runtime must process exactly one request per Execute call.
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	// Health reports whether the capability runtime is ready to accept requests.
	// Called periodically by the runtime backend to detect unresponsive workers.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Shutdown requests graceful termination. The capability runtime should
	// complete any in-flight work and close. The runtime backend will
	// forcefully terminate the process if Shutdown does not complete within a deadline.
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
}

type capabilityRuntimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCapabilityRuntimeServiceClient(cc grpc.ClientConnInterface) CapabilityRuntimeServiceClient {
	return &capabilityRuntimeServiceClient{cc}
}

func (c *capabilityRuntimeServiceClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeResponse)
	err := c.cc.Invoke(ctx, CapabilityRuntimeService_Initialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capabilityRuntimeServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, CapabilityRuntimeService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capabilityRuntimeServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, CapabilityRuntimeService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capabilityRuntimeServiceClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, CapabilityRuntimeService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CapabilityRuntimeServiceServer is the server API for CapabilityRuntimeService service.
// All implementations must embed UnimplementedCapabilityRuntimeServiceServer
// for forward compatibility.
//
// CapabilityRuntimeService is the gRPC contract that capability runtime
// processes implement. N.O.R.E. acts as the client; the capability runtime
// process acts as the server. This protocol is language-independent:
// capability runtime authors can implement it in Go, C#, Java, Rust, Python,
// C++, or any language with gRPC support.
//
// The lifecycle is:
//  1. N.O.R.E. starts the capability runtime process (or connects to one).
//  2. N.O.R.E. calls Initialize to negotiate protocol version and exchange identity.
//  3. N.O.R.E. calls Execute for each execution request.
//  4. N.O.R.E. periodically calls Health to verify the runtime is alive.
//  5. N.O.R.E. calls Shutdown for graceful termination.
type CapabilityRuntimeServiceServer interface {
	// Initialize negotiates the protocol version and exchanges capability
	// runtime identity.
	// Called once per capability runtime process lifetime, before any Execute calls.
	Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error)
	// Execute runs one capability execution and returns the result.
	// The runtime must process exactly one request per Execute call.
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	// Health reports whether the capability runtime is ready to accept requests.
	// Called periodically by the runtime backend to detect unresponsive workers.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Shutdown requests graceful termination. The capability runtime should
	// complete any in-flight work and close. The runtime backend will
	// forcefully terminate the process if Shutdown does not complete within a deadline.
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	mustEmbedUnimplementedCapabilityRuntimeServiceServer()
}

// UnimplementedCapabilityRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCapabilityRuntimeServiceServer struct{}

func (UnimplementedCapabilityRuntimeServiceServer) Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedCapabilityRuntimeServiceServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedCapabilityRuntimeServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedCapabilityRuntimeServiceServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedCapabilityRuntimeServiceServer) mustEmbedUnimplementedCapabilityRuntimeServiceServer() {
}
func (UnimplementedCapabilityRuntimeServiceServer) testEmbeddedByValue() {}

// UnsafeCapabilityRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CapabilityRuntimeServiceServer will
// result in compilation errors.
type UnsafeCapabilityRuntimeServiceServer interface {
	mustEmbedUnimplementedCapabilityRuntimeServiceServer()
}

func RegisterCapabilityRuntimeServiceServer(s grpc.ServiceRegistrar, srv CapabilityRuntimeServiceServer) {
	// If the following call panics, it indicates UnimplementedCapabilityRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CapabilityRuntimeService_ServiceDesc, srv)
}

func _CapabilityRuntimeService_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilityRuntimeServiceServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapabilityRuntimeService_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilityRuntimeServiceServer).Initialize(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapabilityRuntimeService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilityRuntimeServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapabilityRuntimeService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilityRuntimeServiceServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapabilityRuntimeService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilityRuntimeServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapabilityRuntimeService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilityRuntimeServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapabilityRuntimeService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilityRuntimeServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapabilityRuntimeService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilityRuntimeServiceServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CapabilityRuntimeService_ServiceDesc is the grpc.ServiceDesc for CapabilityRuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CapabilityRuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "neuron.capability_runtime.v1.CapabilityRuntimeService",
	HandlerType: (*CapabilityRuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Initialize",
			Handler:    _CapabilityRuntimeService_Initialize_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _CapabilityRuntimeService_Execute_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _CapabilityRuntimeService_Health_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _CapabilityRuntimeService_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shared/protocol/capabilityruntime/v1/capability_runtime.proto",
}
